user_service_api:
    resource: "@UserServiceBundle/Resources/config/api-routing.yml"
    prefix:   /api

user_service_static_pages:
    resource: "@UserServiceBundle/Resources/config/static-pages.yml"
    prefix:   /static

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

