# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        CommonServices\UserServiceBundle\Security\UserProvider\WebserviceUser:
            algorithm: bcrypt
            cost: 12
        CommonServices\UserServiceBundle\Document\AccessInfo:
            algorithm: bcrypt
            cost: 12

    providers:
        webservice:
            id: user_service.mongodb_user_provider

    firewalls:
        login:
            pattern:  ^/api/user-service/security/login
            stateless: true
            anonymous: true
            provider: webservice
            form_login:
                username_parameter: userName
                password_parameter: password
                check_path: /api/user-service/security/login
                require_previous_session: false
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout: true

        api:
            pattern:  ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/photo-service/file/storage/file,               role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST]  }
        - { path: ^/api/user-service/webhook/send,                     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user-service/webhook/initialize,               role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user-service/changeRequest,                    role: IS_AUTHENTICATED_ANONYMOUSLY } ## login
        - { path: ^/api/user-service/security/forgotPassword,          role: IS_AUTHENTICATED_ANONYMOUSLY } ## login
        - { path: ^/api/user-service/security/login,                   role: IS_AUTHENTICATED_ANONYMOUSLY } ## login
        - { path: ^/api/user-service/info,                             role: IS_AUTHENTICATED_ANONYMOUSLY } ## login
        - { path: ^/api/user-service/user,                             role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] } ## login
        - { path: ^/api/,                                              role: IS_AUTHENTICATED_FULLY }



