# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        CommonServices\UserServiceBundle\Security\UserProvider\WebserviceUser:
            algorithm: bcrypt
            cost: 12
        CommonServices\UserServiceBundle\Document\AccessInfo:
            algorithm: bcrypt
            cost: 12

    providers:
        webservice:
            id: user_service.mongodb_user_provider

    firewalls:
        login:
            pattern:  ^/api/security/login
            stateless: true
            anonymous: true
            provider: webservice
            form_login:
                username_parameter: userName
                password_parameter: password
                check_path: /api/security/login
                require_previous_session: false
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout: true

        api:
            pattern:  ^/api
            stateless: true
            anonymous: true
            lexik_jwt: ~

    access_control:
        - { path: ^/api/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } ## login
        - { path: ^/api, roles: ROLE_USER }



