# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

        # ...

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        security:
            pattern: ^/api/security/(reset-password|request-password)/
            security: false
        common:
            pattern: ^/api/common/
            security: false
        doc:
            pattern: ^/api/doc
            security: false
        jwt_token:
            pattern: ^/api/security/login
            stateless: true
            gfreeau_get_jwt:
                username_parameter: email
                #failure_handler:
        main:
            pattern: ^/
            stateless: true
            lexik_jwt: ~
