version: '2.0'
services:
  server:
      build: ./nginx/
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ../service:/var/www/html
          - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
  php-fpm:
      build: ./php-fpm/
      ports:
          - "9000:9000"
      volumes:
          - ../service:/var/www/html