user_service_sign_in_user:
    methods: [GET]
    path:     /signin
    defaults: { _controller: UserServiceBundle:StaticController/Static:signIn }

user_service_sign_up_user:
    methods: [GET]
    path:     /signup
    defaults: { _controller: UserServiceBundle:StaticController/Static:signUp }

user_service_forgot_password:
    methods: [GET]
    path:     /forgot-password
    defaults: { _controller: UserServiceBundle:StaticController/ForgotPassword:forgotPassword }
