## User related resources
user_service_list_users:
    methods: [GET]
    path:     /user
    defaults: { _controller: UserServiceBundle:UserController/User:listUsers}

user_service_get_user:
    methods: [GET]
    path:     /user/{uuid}
    defaults: { _controller: UserServiceBundle:UserController/User:getUser }

user_service_post_user:
    methods: [POST]
    path:     /user
    defaults:
      _controller: UserServiceBundle:UserController/User:newUser

user_service_put_user:
    methods: [PUT]
    path:     /user/{uuid}
    defaults: { _controller: UserServiceBundle:UserController/User:putUser }

user_service_delete_user:
    methods: [DELETE]
    path:     /user/{uuid}
    defaults: { _controller: UserServiceBundle:UserController/User:deleteUser }

user_service_patch_user:
    methods: [PATCH]
    path:     /user/{uuid}
    defaults: { _controller: UserServiceBundle:UserController/User:patchUser }

## User related resources
user_service_get_user_phone_number:
    methods: [GET]
    path:     /user/{uuid}/mobileNumber
    defaults: { _controller: UserServiceBundle:UserController/UserMobileNumber:getUserPhoneNumber }

## Social accounts resources
user_service_get_user_facebook_account:
    methods: [GET]
    path:     /user/{uuid}/facebookAccount
    defaults: { _controller: UserServiceBundle:SocialAccountController/UserFacebookAccount:getUserFacebookAccount }

user_service_get_user_google_account:
    methods: [GET]
    path:     /user/{uuid}/googleAccount
    defaults: { _controller: UserServiceBundle:SocialAccountController/UserGoogleAccount:getUserGoogleAccount }