user_service_list_users:
    methods: [GET]
    path:     /user
    defaults: { _controller: UserServiceBundle:User:listUsers}

user_service_get_user:
    methods: [GET]
    path:     /user/{uuid}
    defaults: { _controller: UserServiceBundle:User:getUser }

user_service_post_user:
    methods: [POST]
    path:     /user/registration/
    defaults:
      _controller: UserServiceBundle:User:newUser

user_service_put_user:
    methods: [PUT]
    path:     /user/{userId}
    defaults: { _controller: UserServiceBundle:User:putUser }

user_service_patch_user:
    methods: [PATCH]
    path:     /user/{userId}
    defaults: { _controller: UserServiceBundle:User:patchUser }

## User related resources
user_service_get_user_phone_number:
    methods: [GET]
    path:     /user/{uuid}/phoneNumber
    defaults: { _controller: UserServiceBundle:User:getUserPhoneNumber }

user_service_get_user_facebook_account:
    methods: [GET]
    path:     /user/{uuid}/facebookAccount
    defaults: { _controller: UserServiceBundle:User:getUserPhoneNumber }

user_service_get_user_google_account:
    methods: [GET]
    path:     /user/{uuid}/googleAccount
    defaults: { _controller: UserServiceBundle:User:getUserPhoneNumber }