#user_service_api:
#    resource: "@UserServiceBundle/Resources/config/routing/api.yml"
#    prefix:   /api

#user_service_static_pages:
#    resource: "@UserServiceBundle/Resources/config/routing/static-pages.yml"
#    prefix:   /static
