imports:
    - { resource: service/aws.yml }
    - { resource: service/cli.yml }
    - { resource: service/document-listener.yml }
    - { resource: service/event-listener.yml }
    - { resource: service/exception.yml }
    - { resource: service/factory.yml }
    - { resource: service/parameter-converter.yml }
    - { resource: service/processor.yml }
    - { resource: service/provider.yml }
    - { resource: service/rabbitmq.yml }
    - { resource: service/request-listener.yml }
    - { resource: service/response-listener.yml }
    - { resource: service/validator.yml }

services:
    ## Core business domains
    user_service.user_domain:
        class: CommonServices\UserServiceBundle\Domain\User\UserDomain
        shared: false
        arguments: ["@service_container",
                    "@=service('doctrine_mongodb').getManager().getRepository('UserServiceBundle:User')"]

    user_service.change_request_domain:
        class: CommonServices\UserServiceBundle\Domain\ChangeRequest\ChangeRequestDomain
        shared: false
        arguments: ["@service_container",
                    "@=service('doctrine_mongodb').getManager().getRepository('UserServiceBundle:ChangeRequest')"]

