services:
    user_service.core:
        class: CommonServices\UserServiceBundle\lib\UserManagerService
        arguments: ["@service_container",
                    "@=service('doctrine_mongodb').getManager().getRepository('UserServiceBundle:User')"]

    user_service.response_serializer:
        class: CommonServices\UserServiceBundle\Serializer\ResponseSerializer
        arguments: ["@service_container", "@jms_serializer.serializer"]

    user_service.exception_handler:
        class: CommonServices\UserServiceBundle\Event\EventHandler\ApiExceptionHandler
        arguments: ["@service_container", "@jms_serializer.serializer"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    user_service.response_listener:
        class: CommonServices\UserServiceBundle\Event\EventListener\ResponseListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    doctrine_mongo_db_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: ["@doctrine_mongodb"]
        tags:
            - { name: request.param_converter, converter: doctrine.odm }

    doctrine_mongo_db_pre_persisit_listener:
        class:   CommonServices\UserServiceBundle\Event\EventListener\Document\DocumentPrePersistListener
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: prePersist }



    ## type processors and transformers
    app.type.user_access_info_type:
        class: CommonServices\UserServiceBundle\Form\Type\AccessInfoType
        arguments: ["@=service('doctrine_mongodb').getManager()"]
        tags:
            - { name: form.type }

    app.type.user_phone_number_type:
        class: CommonServices\UserServiceBundle\Form\Type\PhoneNumberType
        arguments: ["@=service('doctrine_mongodb').getManager()"]
        tags:
            - { name: form.type }

    app.type.user_type:
        class: CommonServices\UserServiceBundle\Form\Type\UserType
        arguments: ["@=service('doctrine_mongodb').getManager()"]
        tags:
            - { name: form.type }
