
## File Storage resource
photo_service_file_upload_policy:
    methods: [GET]
    path:     /file/storage/user/{uuid}
    defaults: { _controller: PhotoBundle:FileStorage:uploadPolicy }



## File Analysis resource
photo_service_file_analysis:
    methods: [POST]
    path:     /file/analysis
    defaults: { _controller: PhotoBundle:FileAnalysis:info}

photo_service_get_file_info:
    methods: [GET]
    path:     /file/{uuid}
    defaults: { _controller: PhotoBundle:FileAnalysis:get}



## Photo resource
photo_service_post_photo:
    methods: [POST]
    path:     /photo
    defaults: { _controller: PhotoBundle:Photo:newPhoto }

photo_service_list_photos:
    methods: [GET]
    path:     /photo
    defaults: { _controller: PhotoBundle:Photo:list}

photo_service_get_photo:
    methods: [GET]
    path:     /photo/{uuid}
    defaults: { _controller: PhotoBundle:Photo:list }

photo_service_update_photo:
    methods: [PUT]
    path:     /photo/{uuid}
    defaults: { _controller: PhotoBundle:Photo:list }

photo_service_patch_photo:
    methods: [PATCH]
    path:     /photo/{uuid}
    defaults: { _controller: PhotoBundle:Photo:list }




## Photo categories
photo_service_list_categories:
    methods: [GET]
    path:     /category
    defaults: { _controller: PhotoBundle:Category:list}

photo_service_post_category:
    methods: [POST]
    path:     /category
    defaults: { _controller: PhotoBundle:Category:newCategory }

photo_service_get_category:
    methods: [GET]
    path:     /category/{uuid}
    defaults: { _controller: PhotoBundle:Category:get }

photo_service_delete_category:
    methods: [DELETE]
    path:     /category/{uuid}
    defaults: { _controller: PhotoBundle:Category:delete }

photo_service_update_category:
    methods: [PATCh]
    path:     /category/{uuid}
    defaults: { _controller: PhotoBundle:Category:update }




## Photo Lightbox
photo_service_list_lightboxes:
    methods: [GET]
    path:     /lightbox
    defaults: { _controller: PhotoBundle:Lightbox:list}

photo_service_get_user_lightbox_collection:
    methods: [GET]
    path:     /lightbox/user/{uuid}
    defaults: { _controller: PhotoBundle:Lightbox:getUserLightBoxes }

photo_service_get_lightbox:
    methods: [GET]
    path:     /lightbox/{uuid}
    defaults: { _controller: PhotoBundle:Lightbox:get }

photo_service_create_new_lightbox:
    methods: [POST]
    path:     /lightbox/
    defaults: { _controller: PhotoBundle:Lightbox:newLightBox }

photo_service_delete_lightbox:
    methods: [DELETE]
    path:     /lightbox/{uuid}
    defaults: { _controller: PhotoBundle:Lightbox:delete }

photo_service_update_lightbox:
    methods: [PUT]
    path:     /lightbox/{uuid}
    defaults: { _controller: PhotoBundle:Lightbox:update }

photo_service_add_item_to_lightbox:
    methods: [PATCH]
    path:     /lightbox/{uuid}/item/{item}
    defaults: { _controller: PhotoBundle:Lightbox:addItem }

photo_service_delete_item_from_lightbox:
    methods: [DELETE]
    path:     /lightbox/{uuid}/item/{item}
    defaults: { _controller: PhotoBundle:Lightbox:deleteItem }
