services:
    ## Document prePersist, postPersist, preUpdate events
    doctrine_mongo_db_pre_persisit_listener:
        class:   CommonServices\UserServiceBundle\EventListener\Document\User\UserDocumentPrePersistListener
        arguments: ["@service_container"]
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: prePersist }

    doctrine_mongo_db_post_persisit_listener:
        class:   CommonServices\UserServiceBundle\EventListener\Document\User\UserDocumentPostPersistListener
        arguments: ["@service_container"]
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: postPersist }

    doctrine_mongo_db_perupdate_listener:
        class:   CommonServices\UserServiceBundle\EventListener\Document\User\UserDocumentPreUpdateListener
        arguments: ["@service_container"]
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
