services:
    ## business events
    user_service.user_password_changed_subscriber:
        class:   CommonServices\UserServiceBundle\EventHandler\UserEvent\UserPasswordChangedListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    user_service.user_name_changed_subscriber:
        class:   CommonServices\UserServiceBundle\EventHandler\UserEvent\UserNameChangedListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    user_service.user_mobile_number_changed_subscriber:
        class:   CommonServices\UserServiceBundle\EventHandler\UserEvent\UserMobileNumberChangedListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    user_service.user_account_created_subscriber:
        class:   CommonServices\UserServiceBundle\EventHandler\UserEvent\UserAccountListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    user_service.user_password_change_requested_subscriber:
        class: CommonServices\UserServiceBundle\EventHandler\UserEvent\UserPasswordRetrievalRequestedListener
        arguments:
          - "@service_container"
          - "@user_service.user_domain"
          - "@user_service.change_request_domain"
        tags:
            - { name: kernel.event_subscriber }

    user_service.user_email_changed_subscriber:
        class:   CommonServices\UserServiceBundle\EventHandler\UserEvent\UserEmailEventListener
        arguments:
          - "@service_container"
          - "@user_service.change_request_domain"
        tags:
            - { name: kernel.event_subscriber }
