services:
    ## amqb producer
    user_service.amqb_consumer.user_account_change:
        class: CommonServices\UserServiceBundle\EventBus\Consumer\UserAccountChangeConsumer
        arguments:
            - "@service_container"
