services:
    ## Registered Listeners and subscribers
    user_service.response_listener:
        class: CommonServices\UserServiceBundle\EventListener\ResponseListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    # Serializers and API utilities
    user_service.response_serializer:
        class: CommonServices\UserServiceBundle\Serializer\ResponseSerializer
        arguments: ["@service_container", "@jms_serializer.serializer"]
